# Generated by Django 4.2.5 on 2023-10-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(help_text="The author's first name or names.", max_length=50)),
                ('last_names', models.CharField(help_text="The author's last name or names", max_length=50)),
                ('email', models.EmailField(help_text='The contact email for the author', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the publisher', max_length=50)),
                ('city', models.CharField(help_text='The city where the publisher is located', max_length=25)),
                ('website', models.URLField(help_text="The publisher's website")),
                ('email', models.EmailField(help_text="The publisher's email address", max_length=254)),
            ],
        ),
    ]
