# Generated by Django 4.2.5 on 2023-10-04 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the book.', max_length=70)),
                ('isbn', models.CharField(max_length=20, verbose_name='ISBN number of the book')),
                ('interest_age', models.CharField(choices=[('SEVEN_PLUS', '7+'), ('EIGHT_PLUS', '8+'), ('NINE_PLUS', '9+'), ('TEN_PLUS', '10+'), ('ELEVEN_PLUS', '11+'), ('TWELVE_PLUS', '12+'), ('ELEVEN_TWELVE', '11-12'), ('ELEVEN_FOURTEEN', '11-14'), ('THIRTEEN', '13'), ('THIRTEEN_PLUS', '13+'), ('THIRTEEN_FIFTEEN', '13-15'), ('THIRTEEN_EIGHTEEN', '13-18'), ('FOURTEEN_PLUS', '14+')], max_length=20, verbose_name="The interested readers' age")),
                ('reading_age', models.CharField(choices=[('SEVEN_PLUS', '7+'), ('EIGHT_PLUS', '8+'), ('NINE_PLUS', '9+'), ('TEN_PLUS', '10+'), ('ELEVEN_PLUS', '11+'), ('TWELVE_PLUS', '12+'), ('ELEVEN_TWELVE', '11-12'), ('ELEVEN_FOURTEEN', '11-14'), ('THIRTEEN', '13'), ('THIRTEEN_PLUS', '13+'), ('THIRTEEN_FIFTEEN', '13-15'), ('THIRTEEN_EIGHTEEN', '13-18'), ('FOURTEEN_PLUS', '14+')], max_length=20, verbose_name="The targeted readers' age")),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.publisher')),
            ],
        ),
    ]
